### ISSUE TITLE
dash: VLC

### ISSUE THREAD

**Issue by 89z** [89z/format#5]
It seems media processed by the decryptor does not play in VLC currently.

Further, while it does play with MPC-HC, I have noticed that it is sometimes slow to load on the first playback, while second playback is fast, so could be related. Example command from `89z/mech`:

~~~
amc -b 1010702
~~~

**Comment by 89z** [comment]
https://github.com/89z/mech/issues/78

**Comment by 89z** [comment]
http://download.videolan.org/pub/videolan/vlc/3.0.17.4/win64/

**Comment by 89z** [comment]
> Here's the VLC error:
> 
> ~~~
> Codec not supported:
> VLC could not decode the format "    " (No description for this codec)
> ~~~

@teo4all I think I am able to reproduce this, but how did you get that error? I get the black screen, but no error pops up.

**Comment by teo4all** [comment]
When opening the m4v, I also get the black screen. I get the error if I mux the audio and video with mkvmerge and try to open the mkv file.

**Comment by 89z** [comment]
Hm OK. I am not interested in supporting MkvMerge, but I bet if I fix the VLC problem, then everything else should be fine. I will work on this

**Comment by 89z** [comment]
I did some more testing, I am able to fix this. I have some local code that has fixed the problem. I will see if I can make a commit

**Comment by 89z** [comment]
OK it looks like the issue was with the Init segment. I was copying the Init as is, which works fine with MPC-HC. However VLC requires that encryption be removed from the Init segment as well. I should have a fix soon

**Comment by 89z** [comment]
I added a function to decrypt the init piece:

https://github.com/89z/format/blob/2ec075cd5fe959fa3b8481642fbdfaa5e7bffb0c/dash/decrypt.go#L51

so this should be fixed now. I will see about adding the change in 89z/mech as well

**Comment by 89z** [comment]
FYI I pushed a new commit, so files should work with Mozilla Firefox as well:

https://github.com/89z/format/blob/9f34fb0a5c3dba81eaaaff877c82d6ef95ee66ad/dash/decrypt.go#L69-L70
